---
- name: create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ kompose_download_dir }}'

- name: download Kompose
  get_url:
    url: '{{ kompose_mirror }}/{{ kompose_redis_filename }}'
    dest: '{{ kompose_download_dir }}/{{ kompose_download_filename }}'
    sha256sum: '{{ kompose_redis_sha256sum }}'
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'

- name: create the Kompose staging dir
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ kompose_staging_dir }}'

- name: install unarchive module dependencies (apt, yum, dnf, zypper)
  become: yes
  package:
    name:
      - tar
      - unzip
    state: present
  when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')

- name: extract Kompose
  unarchive:
    src: '{{ kompose_download_dir }}/{{ kompose_download_filename }}'
    remote_src: yes
    dest: '{{ kompose_staging_dir }}'
    creates: '{{ kompose_staging_dir }}/{{ kompose_redis_executable_filename }}'

- name: create the Kompose installation dir
  become: yes
  file:
    state: directory
    dest: '{{ kompose_install_dir }}'

- name: install Kompose
  become: yes
  copy:
    src: '{{ kompose_staging_dir }}/{{ kompose_redis_executable_filename }}'
    remote_src: yes
    dest: '{{ kompose_install_dir }}/kompose'
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
